### ISSUE TITLE
Style doesn't load

### ISSUE THREAD

**Issue by aghili371** [EtchUK/Etch.OrchardCore.Gallery#17]
i think you missd gallery style.

i can not find "list list--gallery js-gallery" style classes

![gallery](https://user-images.githubusercontent.com/24512878/81236464-90f9a880-8ffd-11ea-9f51-dc87879def0d.JPG)

**Comment by peterkeating** [comment]
@aghili371 Module doesn't applying styling out the box, it needs to be defined within your theme. This follows a similar approach to all the modules that come out the box with Orchard Core, the CSS/HTML (and in this case JavaScript), should be handled by the theme.

**Comment by aghili371** [comment]
where i can find the style? do you have any project example?
