### ISSUE TITLE
Add Media failing to run

### ISSUE THREAD

**Issue by pierslawson** [EtchUK/Etch.OrchardCore.Gallery#54]
Sorry... bit of a newbie problem probably. 

I have tried both downloading your code and installing via NuGet. After adding into a site (based on The Agency Theme) using Orchard Core 1.4 and turning on the "Gallery" feature, I can see the Gallery Widget in Content Types. If I add it to a new Content Type and create an instance of that new Content type, I see the Add Media button but it does not do anything.  AFter saving the new Content Item and then editing, the button still does not work.

Am I missing an obvious step?

**Comment by muzzi-w** [comment]
I'm having the same issue. Probably related to https://github.com/OrchardCMS/OrchardCore/issues/11703 and this one https://github.com/Lombiq/Helpful-Extensions/issues/76 too
