### ISSUE TITLE
Currently no media in the gallery

### ISSUE THREAD

**Issue by yassinsayed** [EtchUK/Etch.OrchardCore.Gallery#64]
thanks for providing this module it works fine but when I try to widget with the gallery I can not add media 

Currently no media in the gallery.  see the image attached please advise what is required

note: gallery feature is enabled

![no gellery](https://github.com/EtchUK/Etch.OrchardCore.Gallery/assets/34830420/b392f447-4300-4401-968b-1f43301c3c84)

**Comment by peterkeating** [comment]
@yassinsayed This should be resolved by changes made in https://github.com/EtchUK/Etch.OrchardCore.Gallery/pull/62.
